### ISSUE TITLE
Need helps to use this role to set different setting for different host 

### ISSUE THREAD

**Issue by ozbillwang** [DavidWittman/ansible-filebeat#7]
Suppose I have three applications: web, app and database. How can I create three different profiles with same `DavidWittman/ansible-filebeat` role?

For example, I define a var file as below which will be applied to all servers (`common role`)

```
filebeat_config:
    filebeat:
      prospectors:
        - paths:
            - /var/log/messages
            - /var/log/secure
            - /var/log/*.log
          document_type: syslog
          fields:
             type: syslog
    output:
      elasticsearch:
        hosts:
          - logstash01:6782
          - logstash02:6782
        timeout: 15
        tls: 
          certificate_authorities:
             - /etc/pki/tls/certs/logstash_cert.crt
          certificate: /etc/pki/tls/certs/logstash_cert.crt
          certificate_key: /etc/pki/tls/private/logstash_key.crt
    logging:
      to_syslog: true
      level: error
```

Then I need define a new filebeat config to support type of `apache` for web servers only, what can I do ?

**Comment by DavidWittman** [comment]
@SydOps Where are you defining `filebeat_config`? It seems to make most sense to just put each value in `group_vars` for each of those groups you have.

You can also template out portions of the `filebeat_config` so you don't have to repeat yourself so much:

``` yaml
filebeat_config:
  filebeat:
    prospectors: "{{ filebeat_config_prospectors }}"
  output:
      elasticsearch:
        hosts:
          - logstash01:6782
          - logstash02:6782
        timeout: 15
        tls: 
          certificate_authorities:
             - /etc/pki/tls/certs/logstash_cert.crt
          certificate: /etc/pki/tls/certs/logstash_cert.crt
          certificate_key: /etc/pki/tls/private/logstash_key.crt
    logging:
      to_syslog: true
      level: error

# Then you can just override the templated variable from above so you
# do not have to redefine the whole configuration each time.
filebeat_config_prospectors:
  - paths:
      - /var/log/messages
      - /var/log/secure
      - /var/log/*.log
    document_type: syslog
    fields:
      type: syslog
```

**Comment by ozbillwang** [comment]
the var file is in `inventory/group_vars/all.yml`, that's for common role.

I need add other profiles for different applications. 

see your reply, nice idea. thanks. let me try.

**Comment by ozbillwang** [comment]
@DavidWittman 

Thanks, this works.

**Comment by ozbillwang** [comment]
Finally I prepared the vars file as below to get flexibility with less codes duplicated.

In `all.yml`

```
filebeat_config:
    filebeat:
      prospectors: '{{ filebeat_paths_common + filebeat_paths_extra | default([]) }}'
    output:
      logstash:
        hosts:
          - logstash01:6782
          - logstash02:6782
        timeout: 15
        tls:
          certificate_authorities:
             - /etc/pki/tls/certs/logstash_cert.crt
          certificate: /etc/pki/tls/certs/logstash_cert.crt
          certificate_key: /etc/pki/tls/private/logstash_key.crt
    logging:
      to_syslog: true
      level: error
```

Again, put beow in all.yml:

```
filebeat_paths_common:
  - paths:
      - /var/log/messages
      - /var/log/secure
      - /var/log/*.log
    document_type: syslog
    fields:
      type: syslog
```

Put the application special logs to seperate inventory `group_vars` or `hosts_vars` if required, for example: 

```
filebeat_paths_extra:
  - paths:
      - /var/log/http/access.log
      - /var/log/http/error.log
    document_type: apache
    fields:
      type: apache
```
